<?php

declare(strict_types=1);

namespace App\Module\Example\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The Example module's only table.
 *
 * Generated by `make diff MODULE=Example`, which derives a filter from this
 * module's entity metadata - without it every module's migration contains every
 * table, because `--namespace` chooses only where the file is written.
 */
final class Version20260911160102 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Example: the project table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE example_project (tenant_id UUID NOT NULL, id UUID NOT NULL, name VARCHAR(200) NOT NULL, client_reference TEXT DEFAULT NULL, attributes JSONB NOT NULL, status VARCHAR(16) NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_example_project_tenant ON example_project (tenant_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE example_project');
    }
}
