<?php

declare(strict_types=1);

namespace OpenEnu\Kernel\Crypto;

/**
 * Per-tenant keys derived from one master secret, by HKDF.
 *
 * No key material is stored per tenant: the key for a tenant is a pure function
 * of `APP_ENCRYPTION_KEY` and the tenant id. That means no key table to back up,
 * no bootstrap step when a tenant is created, and no external service required
 * to boot (ADR-0018).
 *
 * The trade is that the master key becomes catastrophic to lose - every
 * encrypted column in every tenant becomes unreadable. It ships in the encrypted
 * backup bundle, and `make buildprod` tells the operator to keep the age private
 * key somewhere that is not the server.
 *
 * Deriving per tenant rather than using one key everywhere means a tenant's data
 * can be made unreadable by rotating that tenant's salt alone - cryptographic
 * erasure, which is a genuinely useful answer to a deletion request.
 */
final class DerivedKeyProvider implements KeyProviderInterface
{
    private const string ALGO = 'sha256';
    private const int KEY_BYTES = 32;

    /** @var array<string, non-empty-string> */
    private array $cache = [];

    public function __construct(private readonly string $masterKey)
    {
        if (\strlen($masterKey) < 32) {
            throw new \InvalidArgumentException(
                'APP_ENCRYPTION_KEY must be at least 32 characters. '
                . 'It is generated by `make env`; a short one means it was set by hand.',
            );
        }
    }

    public function keyFor(?string $tenantId): string
    {
        $salt = $tenantId ?? 'global';

        // Derivation is cheap but not free, and this runs per encrypted field
        // per row. Cached per process, never persisted.
        return $this->cache[$salt] ??= hash_hkdf(
            self::ALGO,
            $this->masterKey,
            self::KEY_BYTES,
            'open-enu:field:v1',
            $salt,
        );
    }
}
