#!/usr/bin/env bash
# =============================================================================
#  The three remediation formats (.ai/platform/PLAN.md §10.4).
# =============================================================================
#  Called by dns-check.sh when anything is missing or wrong. Three files, because
#  three genuinely different workflows exist and none of them should involve
#  retyping an IP address:
#
#    zone.txt        the COMPLETE desired set, for "import and overwrite"
#    cloudflare.sh   only the DELTA, applied by id, safe to re-run
#    records.json    the same desired state, provider-neutral
#
#  Usage: dns-emit.sh DOMAIN TARGET TTL MODE OUTDIR ROW...
#         ROW = status|type|name|current|expected
# =============================================================================
set -uo pipefail

DOMAIN="$1"; TARGET="$2"; TTL="$3"; MODE="$4"; OUT="$5"; shift 5
ROWS=("$@")
TODAY="$(date +%F)"

mkdir -p "$OUT"

# ── 1. zone.txt - the universal import format ───────────────────────────────
# The complete desired set, not the delta: importing with "overwrite existing"
# then converges the zone in one action instead of leaving the wrong records in
# place beside the new ones.
{
  printf '$ORIGIN %s.\n' "$DOMAIN"
  printf '$TTL %s\n' "$TTL"
  printf '; Generated by `make dns-check` - %s - target %s\n' "$TODAY" "$TARGET"
  printf '; Cloudflare: DNS → Records → Import and Export → Import.\n'
  printf ';   WARNING leave "Proxy status" set to DNS only. Proxying breaks Mercure\n'
  printf ';   SSE (api. at minimum - it serves Mercure) and hides the origin from HTTP-01.\n'
  printf '; No SOA and no NS records: your provider owns those, and Cloudflare\n'
  printf '; ignores them on import.\n'

  for row in "${ROWS[@]}"; do
    IFS='|' read -r status type name current expected <<<"$row"
    [ "$type" = "A" ] || continue
    printf '%-10s %-4s IN  A  %s\n' "$name" "$TTL" "$TARGET"
  done

  # Always emitted. An absent CAA is fine, but if one exists and omits Let's
  # Encrypt the zone needs this line, and adding it unconditionally on import is
  # harmless - CAA records are additive.
  printf '%-10s %-4s IN  CAA 0 issue "letsencrypt.org"\n' "@" "$TTL"
} > "$OUT/zone.txt"

# ── 2. records.json - provider-neutral ──────────────────────────────────────
{
  printf '{\n'
  printf '  "domain": "%s", "target": "%s", "mode": "%s", "ttl": %s,\n' "$DOMAIN" "$TARGET" "$MODE" "$TTL"
  printf '  "generated": "%s",\n' "$TODAY"
  printf '  "records": [\n'
  first=1
  for row in "${ROWS[@]}"; do
    IFS='|' read -r status type name current expected <<<"$row"
    # `case`, not `[ … ] || [ … ] && continue`: that reads as (A || B) && C in
    # bash, which happens to be right here and is one edit away from not being.
    case "$status" in ok|warn) continue ;; esac
    [ "$first" -eq 1 ] || printf ',\n'
    first=0
    printf '    { "type": "%s", "name": "%s", "value": "%s", "proxied": false, "status": "%s"' \
      "$type" "$name" "$expected" "$status"
    [ "$status" = "wrong" ] && printf ', "current": "%s"' "$current"
    printf ' }'
  done
  printf '\n  ]\n}\n'
} > "$OUT/records.json"

# ── 3. cloudflare.sh - the delta, applied by id ─────────────────────────────
# A BIND import is blunt: forget the overwrite toggle and it duplicates records.
# This creates what is missing and patches what is wrong, by id, and leaves
# everything else alone.
cat > "$OUT/cloudflare.sh" <<CFEOF
#!/usr/bin/env bash
# Generated by \`make dns-check\` - $TODAY - $DOMAIN → $TARGET
#
#   CF_API_TOKEN=… bash cloudflare.sh           # dry run, prints the calls
#   CF_API_TOKEN=… bash cloudflare.sh --apply   # executes them
#
# The token needs exactly Zone:DNS:Edit on this one zone. It is read from the
# environment and deliberately never written into this file.
set -uo pipefail

API="https://api.cloudflare.com/client/v4"
DOMAIN="$DOMAIN"
TARGET="$TARGET"
TTL=$TTL
APPLY=0
[ "\${1:-}" = "--apply" ] && APPLY=1

: "\${CF_API_TOKEN:?set CF_API_TOKEN - create one at https://dash.cloudflare.com/profile/api-tokens with Zone:DNS:Edit on $DOMAIN}"

cf() { curl -s -H "Authorization: Bearer \$CF_API_TOKEN" -H 'Content-Type: application/json' "\$@"; }

zone_id="\$(cf "\$API/zones?name=\$DOMAIN" | python3 -c 'import json,sys; z=json.load(sys.stdin)["result"]; print(z[0]["id"] if z else "")')"
if [ -z "\$zone_id" ]; then
  echo "  ✗ no Cloudflare zone for \$DOMAIN, or the token cannot see it (needs Zone:DNS:Edit)" >&2
  exit 1
fi

upsert() { # <type> <name> <value>
  local type="\$1" name="\$2" value="\$3" fqdn="\$DOMAIN"
  [ "\$name" != "@" ] && fqdn="\$name.\$DOMAIN"

  local existing
  existing="\$(cf "\$API/zones/\$zone_id/dns_records?type=\$type&name=\$fqdn" \\
    | python3 -c 'import json,sys; r=json.load(sys.stdin)["result"]; print(r[0]["id"]+" "+str(r[0]["content"]) if r else "")')"
  local id="\${existing%% *}" current="\${existing#* }"

  if [ -n "\$id" ] && [ "\$current" = "\$value" ]; then
    echo "  · \$type \$fqdn already \$value"
    return 0
  fi

  # proxied is set explicitly on every record: the orange cloud breaks Mercure
  # SSE and hides the origin from HTTP-01 validation.
  local body
  body="\$(printf '{"type":"%s","name":"%s","content":"%s","ttl":%s,"proxied":false}' "\$type" "\$fqdn" "\$value" "\$TTL")"

  if [ -n "\$id" ]; then
    echo "  ~ \$type \$fqdn  \$current → \$value"
    [ "\$APPLY" -eq 1 ] && cf -X PATCH "\$API/zones/\$zone_id/dns_records/\$id" -d "\$body" >/dev/null
  else
    echo "  + \$type \$fqdn  → \$value"
    [ "\$APPLY" -eq 1 ] && cf -X POST "\$API/zones/\$zone_id/dns_records" -d "\$body" >/dev/null
  fi
}

[ "\$APPLY" -eq 1 ] || echo "  (dry run - pass --apply to execute)"

CFEOF

for row in "${ROWS[@]}"; do
  IFS='|' read -r status type name current expected <<<"$row"
  case "$status" in
    missing|wrong) ;;
    *) continue ;;
  esac

  if [ "$type" = "CAA" ]; then
    # Not upserted: a wrong CAA is somebody's deliberate policy, and silently
    # rewriting it is not this script's business.
    {
      printf 'echo "  ! CAA on %s currently reads: %s"\n' "$DOMAIN" "$current"
      printf 'echo "    Add:  %s 0 issue \\"letsencrypt.org\\"   - or issuance will keep failing."\n' "$DOMAIN"
    } >> "$OUT/cloudflare.sh"
    continue
  fi

  printf 'upsert "%s" "%s" "%s"\n' "$type" "$name" "$expected" >> "$OUT/cloudflare.sh"
done

printf '\n[ "$APPLY" -eq 1 ] && echo "  ✓ applied - DNS may take a few minutes to propagate"\n' >> "$OUT/cloudflare.sh"
chmod +x "$OUT/cloudflare.sh"
