#!/usr/bin/env bash
# =============================================================================
#  Environment generation - .ai/platform/PLAN.md §11
# =============================================================================
#  .env is the only file edited by hand. Every per-app env file is DERIVED from
#  it, so api.${DOMAIN}, CORS origins and Mercure URLs cannot drift apart.
#
#  Two invariants, both load-bearing:
#    1. An existing value is never overwritten. This is what makes `buildprod`
#       safe to re-run against a live server.
#    2. A key added to .env.example upstream is reported (and, for generated
#       secrets, filled) on the next run - so a new variable surfaces as a
#       message, not as a 3am runtime crash.
#
#  Usage: envgen.sh generate   # create/repair .env, then write per-app files
#         envgen.sh check      # read-only drift report; exit 1 if keys missing
# =============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=log.sh
. "$HERE/log.sh"; . "$HERE/secrets.sh"

ENV_FILE="$ROOT/.env"
ENV_EXAMPLE="$ROOT/.env.example"

# ── helpers ─────────────────────────────────────────────────────────────────

# Keys declared in a file, in order.
env_keys() { grep -oE '^[A-Z_][A-Z0-9_]*=' "$1" | tr -d '=' ; }

# Value of a key, read literally (no shell evaluation of the file).
env_get() {
  local key="$1" file="$2"
  sed -n "s/^${key}=//p" "$file" | head -1
}

env_set() {
  local key="$1" val="$2" file="$3"
  local esc; esc=$(printf '%s' "$val" | sed -e 's/[\/&|]/\\&/g')
  if grep -qE "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${esc}|" "$file"
  else
    printf '%s=%s\n' "$key" "$val" >> "$file"
  fi
}

# ── 1. create or repair .env ────────────────────────────────────────────────

ensure_env_file() {
  if [ ! -f "$ENV_FILE" ]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    log_ok "created .env from .env.example"
  else
    chmod 600 "$ENV_FILE"
    log_skip ".env exists - existing values preserved"
  fi

  # Append keys that upstream added to .env.example but this .env lacks.
  local added=0 key
  while read -r key; do
    [ -n "$key" ] || continue
    if ! grep -qE "^${key}=" "$ENV_FILE"; then
      local default; default=$(env_get "$key" "$ENV_EXAMPLE")
      printf '%s=%s\n' "$key" "$default" >> "$ENV_FILE"
      log_warn "new variable added from .env.example: $key"
      added=$((added + 1))
    fi
  done < <(env_keys "$ENV_EXAMPLE")
  [ "$added" -gt 0 ] && log_info "review the $added new value(s) in .env"

  # Host identity, so containers can write into the bind mount as this user
  # rather than as root. Refreshed every run: a checkout copied between machines
  # would otherwise keep the previous machine's uid.
  env_set HOST_UID "$(id -u)" "$ENV_FILE"
  env_set HOST_GID "$(id -g)" "$ENV_FILE"

  # Fill generated secrets. Only ever touches literal __GENERATE__ markers.
  local filled=0
  while read -r key; do
    [ -n "$key" ] || continue
    if [ "$(env_get "$key" "$ENV_FILE")" = "__GENERATE__" ]; then
      env_set "$key" "$(gen_secret 32)" "$ENV_FILE"
      filled=$((filled + 1))
    fi
  done < <(env_keys "$ENV_FILE")
  [ "$filled" -gt 0 ] && log_ok "generated $filled secret(s)"
  return 0
}

# ── 2. derive the per-app env files ─────────────────────────────────────────

write_derived() {
  # Split across lines so the directive below sits directly above the command
  # it annotates: on one line it would apply to `set -a` and the source would
  # still be flagged.
  set -a
  # The path is computed, and the file is the one this script just created or
  # repaired, so there is nothing for a linter to follow.
  # shellcheck source=/dev/null
  . "$ENV_FILE"
  set +a

  local api="https://api.${DOMAIN}"
  # On the API's host, not a mercure. subdomain: the subscriber cookie can then
  # be host-only. A cookie shared by two sibling hosts needs Domain=.${DOMAIN},
  # which also reaches every host beneath it - a staging stack included.
  local mercure="https://api.${DOMAIN}/.well-known/mercure"
  local app_url="https://app.${DOMAIN}"
  local manager_url="https://manager.${DOMAIN}"
  local site_url="https://${DOMAIN}"
  local banner="# GENERATED by \`make env\` from .env - DO NOT EDIT.
# Edit .env instead and re-run; every value here is derived from it.
# See .ai/platform/PLAN.md §11."

  # ── backend ───────────────────────────────────────────────────────────────
  mkdir -p "$ROOT/backend"
  cat > "$ROOT/backend/.env.local" <<EOF
$banner

APP_ENV=${APP_ENV}
APP_DEBUG=${APP_DEBUG}
APP_STAGE=${APP_STAGE}
APP_SECRET=${APP_SECRET}

DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?serverVersion=16&charset=utf8"
REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379"

# Domain events ride the Doctrine transport so they commit in the same
# transaction as the write that raised them (.ai/platform/PLAN.md §6.8). Redis carries only
# fire-and-forget jobs. Failures land in Doctrine so they stay readable.
MESSENGER_TRANSPORT_OUTBOX="doctrine://default?queue_name=outbox"
MESSENGER_TRANSPORT_JOBS="\${REDIS_URL}/jobs"
MESSENGER_TRANSPORT_FAILED="doctrine://default?queue_name=failed"

MAILER_DSN=${MAILER_DSN}
MAILER_FROM=${MAILER_FROM}
MAILER_REPLY_TO=${MAILER_REPLY_TO}

MERCURE_URL=http://mercure/.well-known/mercure
MERCURE_PUBLIC_URL=${mercure}
MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}

JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=${JWT_PASSPHRASE}

APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY}

STORAGE_DSN=${STORAGE_DSN}
STORAGE_MAX_UPLOAD_MB=${STORAGE_MAX_UPLOAD_MB}

# Base URI for URLs generated outside an HTTP request (CLI commands, workers,
# email links). Without this they come out as http://localhost and every link
# in an email is wrong in a way nobody notices until a user clicks one.
DEFAULT_URI=${api}
# Also the CORS allowlist: nelmio_cors names these two variables directly, so
# the origins the browser is allowed to call from cannot drift from the URLs the
# apps are actually served at. Exact origins, never a wildcard - auth rides on
# cookies, so Access-Control-Allow-Credentials is on and a browser refuses a
# wildcard alongside it (.ai/platform/PLAN.md §5).
APP_URL=${app_url}
MANAGER_URL=${manager_url}
SITE_URL=${site_url}

SENTRY_DSN=${SENTRY_DSN}
OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
EOF

  # Symfony deliberately skips .env.local when APP_ENV=test, so the test suite
  # never inherits a developer's machine. It does load .env.test.local, which is
  # where credentials the tests genuinely need belong - generated, gitignored,
  # and never the committed .env.test.
  cat > "$ROOT/backend/.env.test.local" <<EOF
$banner

DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?serverVersion=16&charset=utf8"
REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379"

# The suite issues real tokens against the real keypair, so signing must work -
# stubbing it out would leave the whole authentication path untested.
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=${JWT_PASSPHRASE}
MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}
EOF

  # ── the three Nuxt apps ───────────────────────────────────────────────────
  cat > "$ROOT/frontend/.env" <<EOF
$banner

NUXT_PUBLIC_API_BASE=${api}
NUXT_PUBLIC_MERCURE_URL=${mercure}
NUXT_PUBLIC_APP_NAME=${PROJECT_NAME}
NUXT_PUBLIC_DOMAIN=${DOMAIN}
NUXT_PUBLIC_SITE_URL=${site_url}
NUXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
EOF

  cat > "$ROOT/manager/.env" <<EOF
$banner

NUXT_PUBLIC_API_BASE=${api}
NUXT_PUBLIC_MERCURE_URL=${mercure}
NUXT_PUBLIC_APP_NAME=${PROJECT_NAME} Manager
NUXT_PUBLIC_DOMAIN=${DOMAIN}
NUXT_PUBLIC_APP_URL=${app_url}
NUXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
EOF

  # Only production may be indexed. A staging server is the same site on a
  # public hostname, and one that ranks next to production is a bug with a
  # long half-life. Anything that is not exactly "production" says no.
  local indexable=false
  [ "${APP_STAGE:-}" = production ] && indexable=true

  cat > "$ROOT/landing/.env" <<EOF
$banner

NUXT_PUBLIC_APP_NAME=${PROJECT_NAME}
NUXT_PUBLIC_APP_URL=${app_url}
NUXT_PUBLIC_SITE_URL=${site_url}
NUXT_PUBLIC_DOMAIN=${DOMAIN}
NUXT_PUBLIC_INDEXABLE=${indexable}
EOF

  cat > "$ROOT/e2e/.env" <<EOF
$banner

E2E_APP_URL=${app_url}
E2E_MANAGER_URL=${manager_url}
E2E_API_BASE=${api}
E2E_SITE_URL=${site_url}
EOF

  log_ok "derived backend/.env{.local,.test.local}, frontend/.env, manager/.env, landing/.env, e2e/.env"
}

# ── 3. drift check (read-only) ──────────────────────────────────────────────

check_env() {
  [ -f "$ENV_FILE" ] || die ".env does not exist" "run: make env"

  local missing=() unset_secrets=() key
  while read -r key; do
    [ -n "$key" ] || continue
    grep -qE "^${key}=" "$ENV_FILE" || missing+=("$key")
  done < <(env_keys "$ENV_EXAMPLE")

  while read -r key; do
    [ -n "$key" ] || continue
    [ "$(env_get "$key" "$ENV_FILE")" = "__GENERATE__" ] && unset_secrets+=("$key")
  done < <(env_keys "$ENV_FILE")

  local rc=0
  if [ ${#missing[@]} -gt 0 ]; then
    log_fail "${#missing[@]} variable(s) in .env.example are missing from .env" \
      "${missing[*]}" "run: make env" || true
    rc=1
  fi
  if [ ${#unset_secrets[@]} -gt 0 ]; then
    log_fail "${#unset_secrets[@]} secret(s) still set to __GENERATE__" \
      "${unset_secrets[*]}" "run: make env" || true
    rc=1
  fi
  [ $rc -eq 0 ] && log_ok ".env is complete (${#missing[@]} missing, 0 placeholders)"
  return $rc
}

# ── entrypoint ──────────────────────────────────────────────────────────────
case "${1:-generate}" in
  generate) ensure_env_file; write_derived ;;
  check)    check_env ;;
  *)        die "unknown command: $1" "usage: envgen.sh [generate|check]" ;;
esac
