#!/usr/bin/env bash
# =============================================================================
#  The edge - one Traefik shared by every stack on this Docker host.
# =============================================================================
#  edge.sh up       start the edge if it is not running; register this stack
#                   with it
#  edge.sh attach   join the edge to this stack's network, with this stack's
#                   hostnames as aliases
#  edge.sh detach   leave this stack's network (before `compose down`)
#  edge.sh logs     follow the edge's log
#
#  Two modes, chosen by APP_STAGE in .env:
#
#    local                 mkcert certificates, dashboard at traefik.${DOMAIN},
#                          state in ~/.local/share/enu-edge
#    staging | production  Let's Encrypt, security headers and a rate limit on
#                          every request, no dashboard, state in /opt/enu-edge.
#                          A staging stack also registers its IP allowlist -
#                          refusing to start without one, because it is the dev
#                          stack and must not be public.
#
#  Why the edge joins each stack's network instead of each stack joining one
#  shared network: containers must reach https://app.${DOMAIN} the way a
#  browser does - the e2e runner, and the API delivering a webhook to
#  webhook-echo. Network aliases are what resolve those names inside Docker,
#  and an alias belongs to one container on one network. So the edge carries a
#  stack's aliases on that stack's network, and nowhere else.
#
#  The alternative, extra_hosts pointing at the host gateway, sends that traffic
#  out of Docker and back in through the host, where a firewall can drop it.
#  The failure looks like a TLS or routing bug, which is the worst kind.
#
#  See .ai/platform/specs/2026-09-17-open-enu-and-shared-edge.md and
#  .ai/platform/specs/2026-09-17-staging-and-promotion.md.
# =============================================================================
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
. "$HERE/../lib/log.sh"

EDGE=enu-edge

[ -f "$ROOT/.env" ] || die ".env is missing" "run: make env"
env_value() { sed -n "s/^$1=//p" "$ROOT/.env" | head -1; }
DOMAIN="$(env_value DOMAIN)"
STACK="$(env_value STACK)"; STACK="${STACK:-$(env_value PROJECT_SLUG)}"
STAGE="$(env_value APP_STAGE)"; STAGE="${STAGE:-local}"
[ -n "$DOMAIN" ] && [ -n "$STACK" ] || die "DOMAIN and STACK must be set in .env"
NET="${STACK}-net"

case "$STAGE" in
  local) MODE=local;  DEFAULT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/enu-edge" ;;
  *)     MODE=server; DEFAULT_HOME=/opt/enu-edge ;;
esac
export EDGE_HOME="${EDGE_HOME:-$DEFAULT_HOME}"

edge_state() { docker inspect -f '{{.State.Status}}' "$EDGE" 2>/dev/null; }
edge_health() { docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$EDGE" 2>/dev/null; }
on_network() { docker inspect -f '{{range $n, $_ := .NetworkSettings.Networks}}{{$n}} {{end}}' "$EDGE" 2>/dev/null | tr ' ' '\n' | grep -qxF "$NET"; }

# write_atomically <path> - stdin to <path> via a temp file, so Traefik's
# watcher never reads half a file.
write_atomically() {
  local tmp; tmp="$(mktemp "$(dirname "$1")/.$(basename "$1").XXXXXX")" || return 1
  cat > "$tmp" && chmod 644 "$tmp" && mv "$tmp" "$1"
}

# ── what this stack tells the edge ──────────────────────────────────────────
register_local() {
  local cert="$ROOT/docker/certs/local-cert.pem" key="$ROOT/docker/certs/local-key.pem"
  [ -f "$cert" ] && [ -f "$key" ] || die "no certificate for $DOMAIN" "run: make certs"
  mkdir -p "$EDGE_HOME/certs/$STACK"
  install -m 644 "$cert" "$EDGE_HOME/certs/$STACK/local-cert.pem"
  install -m 600 "$key"  "$EDGE_HOME/certs/$STACK/local-key.pem"

  write_atomically "$EDGE_HOME/dynamic/$STACK.yml" <<EOF
# GENERATED by scripts/dev/edge.sh for '$STACK' from $ROOT - do not edit.
tls:
  certificates:
    - certFile: /certs/$STACK/local-cert.pem
      keyFile: /certs/$STACK/local-key.pem
http:
  routers:
    $STACK-dashboard:
      rule: Host(\`traefik.$DOMAIN\`)
      entryPoints: [websecure]
      tls: {}
      service: api@internal
EOF
  log_ok "registered *.$DOMAIN with the edge (mkcert)"
}

register_server() {
  install -m 644 "$ROOT/docker/edge/middlewares.yml" "$EDGE_HOME/dynamic/_shared.yml"

  if [ "$STAGE" = staging ]; then
    local allow; allow="$(env_value STAGING_ALLOW_FROM | tr -d ' ')"
    [ -n "$allow" ] || die "STAGING_ALLOW_FROM is empty in .env" \
      "staging runs the dev stack - the profiler shows environment variables and Vite serves source files" \
      "it will not be exposed to everyone; set your IP (or a CIDR) and re-run"
    {
      printf "# GENERATED by scripts/dev/edge.sh for '%s' from %s - do not edit.\n" "$STACK" "$ROOT"
      printf "# Edit STAGING_ALLOW_FROM in that .env and run: make edge\n"
      printf "http:\n  middlewares:\n    %s-allow:\n      ipAllowList:\n        sourceRange:\n" "$STACK"
      tr ',' '\n' <<<"$allow" | sed '/^$/d; s/^/          - "/; s/$/"/'
    } | write_atomically "$EDGE_HOME/dynamic/$STACK.yml"
    log_ok "staging is reachable only from: $allow"
  else
    rm -f "$EDGE_HOME/dynamic/$STACK.yml"
    log_ok "registered $DOMAIN with the edge (Let's Encrypt)"
  fi
}

# render_static <dest> - the static config this mode wants.
render_static() {
  if [ "$MODE" = local ]; then
    cat "$ROOT/docker/edge/traefik.yml"
    return
  fi
  local email ca
  email="$(env_value LETSENCRYPT_EMAIL)"
  ca="$(env_value LE_CA_SERVER)"; ca="${ca:-https://acme-v02.api.letsencrypt.org/directory}"
  [ -n "$email" ] || die "LETSENCRYPT_EMAIL is empty in .env" \
    "ACME registration fails without it, and nothing gets a certificate"
  sed -e "s|__LETSENCRYPT_EMAIL__|$email|" -e "s|__LE_CA_SERVER__|$ca|" "$ROOT/docker/edge/traefik.server.yml"
}

# ── up ──────────────────────────────────────────────────────────────────────
cmd_up() {
  log_step "Edge - $EDGE ($MODE, $EDGE_HOME)"
  mkdir -p "$EDGE_HOME/dynamic" "$EDGE_HOME/certs" "$EDGE_HOME/acme" 2>/dev/null \
    || die "cannot create $EDGE_HOME" "on a server: sudo mkdir -p $EDGE_HOME && sudo chown \$USER $EDGE_HOME"

  # Two modes on one Docker host would mean a server edge serving mkcert
  # certificates, or a laptop requesting Let's Encrypt ones for .local names.
  local marker="$EDGE_HOME/mode"
  if [ -f "$marker" ] && [ "$(cat "$marker")" != "$MODE" ]; then
    die "the edge at $EDGE_HOME runs in $(cat "$marker") mode, and this stack needs $MODE" \
      "a local and a server stack cannot share one Docker host"
  fi
  echo "$MODE" > "$marker"

  if [ "$MODE" = local ]; then register_local; else register_server; fi

  local static="$EDGE_HOME/traefik.yml" rendered static_changed=0
  rendered="$(render_static)" || exit 1
  if [ "$rendered" != "$(cat "$static" 2>/dev/null)" ]; then
    printf '%s\n' "$rendered" | write_atomically "$static"
    static_changed=1
  fi
  if [ "$MODE" = server ]; then
    touch "$EDGE_HOME/acme/acme.json" && chmod 600 "$EDGE_HOME/acme/acme.json"
  fi

  # The image the compose file pins, against the one the running edge was made
  # from. `running` used to mean "leave it": a Traefik bump in the repo then
  # never reached a host that already had an edge - a server included, where a
  # patch release is usually a security fix.
  local want_image have_image
  want_image="$(docker compose -f "$ROOT/docker/edge/compose.yml" config --images 2>/dev/null | head -1)"
  have_image="$(docker inspect -f '{{.Config.Image}}' "$EDGE" 2>/dev/null)"

  case "$(edge_state)" in
    running)
      if [ -n "$want_image" ] && [ "$want_image" != "$have_image" ]; then
        log_warn "the edge runs $have_image, the repo pins $want_image - recreating it (every stack on this host blinks)"
        # A new container keeps none of the old one's network attachments, and
        # each stack attached itself with its own aliases (cmd_attach). Without
        # this, every stack on the host answers 000 until its next `make up`.
        local saved
        saved="$(docker inspect -f '{{range $n, $v := .NetworkSettings.Networks}}{{$n}}{{range $v.Aliases}} {{.}}{{end}}{{println}}{{end}}' "$EDGE")"
        docker compose -f "$ROOT/docker/edge/compose.yml" up -d >/dev/null 2>&1 \
          || die "could not recreate $EDGE on $want_image" "run: EDGE_HOME=$EDGE_HOME docker compose -f docker/edge/compose.yml up -d"
        reattach "$saved"
      elif [ "$static_changed" -eq 1 ]; then
        log_warn "the edge's static config changed - restarting it (every stack on this host blinks)"
        docker restart "$EDGE" >/dev/null || die "could not restart $EDGE"
      else
        log_skip "$EDGE already running ($have_image)"
      fi
      ;;
    *)
      # Name who holds the ports: "port is already allocated" from Docker says
      # nothing about which of a dozen containers to stop.
      local holder
      holder="$(docker ps --filter publish=443 --format '{{.Names}}' | grep -vxF "$EDGE" | head -1)"
      if [ -n "$holder" ]; then
        die "port 443 is held by the container '$holder'" \
          "the edge needs 80 and 443 for itself; stop that container first: docker stop $holder" \
          "(a per-stack Traefik from before the edge existed is exactly this - see troubleshooting.md)"
      fi
      docker compose -f "$ROOT/docker/edge/compose.yml" up -d >/dev/null 2>&1 \
        || die "the edge did not start" "run: EDGE_HOME=$EDGE_HOME docker compose -f docker/edge/compose.yml up -d"
      ;;
  esac

  local i=0 state
  while [ "$i" -lt 60 ]; do
    state="$(edge_health)"
    [ "$state" = healthy ] && { log_ok "$EDGE (healthy)"; return 0; }
    [ "$state" = exited ] && die "$EDGE exited" "inspect: docker logs $EDGE"
    sleep 1; i=$((i + 1))
  done
  die "$EDGE did not become healthy within 60s (last state: ${state:-unknown})" "inspect: docker logs $EDGE"
}

# reattach <saved> - reconnect the edge to every network in <saved>, one line
# per network: "<network> <alias> <alias>...", as read from the old container.
reattach() {
  local net rest a args attached
  attached="$(docker inspect -f '{{range $n, $v := .NetworkSettings.Networks}}{{$n}} {{end}}' "$EDGE")"
  while read -r net rest; do
    [ -n "$net" ] || continue
    case " $attached " in *" $net "*) continue ;; esac   # compose re-created its own
    docker network inspect "$net" >/dev/null 2>&1 || { log_warn "network $net is gone - not reattaching"; continue; }
    args=()
    for a in $rest; do args+=(--alias "$a"); done
    if docker network connect "${args[@]}" "$net" "$EDGE" >/dev/null 2>&1; then
      log_ok "reattached $EDGE to $net"
    else
      log_warn "could not reattach $EDGE to $net - run \`make up\` in that stack"
    fi
  done <<<"$1"
}

# ── attach ──────────────────────────────────────────────────────────────────
cmd_attach() {
  [ -n "$(edge_state)" ] || die "$EDGE does not exist" "run: make edge"
  docker network inspect "$NET" >/dev/null 2>&1 || die "network $NET does not exist" "run: make up"

  # Always reconnect: aliases are fixed at connect time, so an attachment made
  # before `make init` changed the domain would keep answering to the old one.
  on_network && docker network disconnect "$NET" "$EDGE" >/dev/null 2>&1

  local aliases=() h
  for h in "$DOMAIN" "www.$DOMAIN" app manager api mail webhook-echo traefik; do
    case "$h" in *.*) aliases+=(--alias "$h") ;; *) aliases+=(--alias "$h.$DOMAIN") ;; esac
  done
  docker network connect "${aliases[@]}" "$NET" "$EDGE" \
    || die "could not attach $EDGE to $NET"
  log_ok "$EDGE answers for *.$DOMAIN on $NET"
}

# ── detach ──────────────────────────────────────────────────────────────────
cmd_detach() {
  # Compose cannot remove a network that still has the edge on it, and reports
  # it as a warning that is easy to miss - then the next `up` reuses a network
  # nobody meant to keep.
  if on_network; then
    docker network disconnect "$NET" "$EDGE" >/dev/null 2>&1 && log_ok "$EDGE left $NET"
  fi
  return 0
}

case "${1:-}" in
  up)     cmd_up ;;
  attach) cmd_attach ;;
  detach) cmd_detach ;;
  logs)   exec docker logs -f --tail=100 "$EDGE" ;;
  *)      die "usage: edge.sh up|attach|detach|logs" ;;
esac
